# Update sun icons: full circle sun + sun rays instead of glow

$file = 'app/src/main/java/com/j4/diabetestracker/MainActivity.kt'
$lines = Get-Content $file

Write-Host "Adding full sun with rays..."

$newLines = @()
$skipUntilEvening = $false

for ($i = 0; $i -lt $lines.Count; $i++) {
    $line = $lines[$i]
    
    # Replace from "object TimeIcons" until "val Evening"
    if ($line -match 'object TimeIcons') {
        $skipUntilEvening = $true
        # Add corrected TimeIcons with full sun and rays
        $newLines += "object TimeIcons {"
        $newLines += "    val Morning: ImageVector"
        $newLines += "        get() = ImageVector.Builder("
        $newLines += "            name = `"Morning`","
        $newLines += "            defaultWidth = 24.0.dp,"
        $newLines += "            defaultHeight = 24.0.dp,"
        $newLines += "            viewportWidth = 24.0f,"
        $newLines += "            viewportHeight = 24.0f"
        $newLines += "        ).apply {"
        $newLines += "            // Sun rays (8 rays)"
        $newLines += "            path("
        $newLines += "                fill = androidx.compose.ui.graphics.SolidColor(androidx.compose.ui.graphics.Color(0xFFFFE082)),"
        $newLines += "                fillAlpha = 0.7f"
        $newLines += "            ) {"
        $newLines += "                // Ray 1 (top)"
        $newLines += "                moveTo(15f, 8f)"
        $newLines += "                lineTo(15.5f, 6f)"
        $newLines += "                lineTo(14.5f, 6f)"
        $newLines += "                close()"
        $newLines += "                // Ray 2 (top-right)"
        $newLines += "                moveTo(16.5f, 9f)"
        $newLines += "                lineTo(18f, 7.5f)"
        $newLines += "                lineTo(17f, 7f)"
        $newLines += "                close()"
        $newLines += "                // Ray 3 (right)"
        $newLines += "                moveTo(18f, 11f)"
        $newLines += "                lineTo(20f, 11f)"
        $newLines += "                lineTo(20f, 10f)"
        $newLines += "                close()"
        $newLines += "                // Ray 4 (bottom-right)"
        $newLines += "                moveTo(16.5f, 13f)"
        $newLines += "                lineTo(18f, 14.5f)"
        $newLines += "                lineTo(17f, 15f)"
        $newLines += "                close()"
        $newLines += "                // Ray 5 (bottom)"
        $newLines += "                moveTo(15f, 14f)"
        $newLines += "                lineTo(15.5f, 16f)"
        $newLines += "                lineTo(14.5f, 16f)"
        $newLines += "                close()"
        $newLines += "                // Ray 6 (bottom-left)"
        $newLines += "                moveTo(13.5f, 13f)"
        $newLines += "                lineTo(12f, 14.5f)"
        $newLines += "                lineTo(13f, 15f)"
        $newLines += "                close()"
        $newLines += "                // Ray 7 (left)"
        $newLines += "                moveTo(12f, 11f)"
        $newLines += "                lineTo(10f, 11f)"
        $newLines += "                lineTo(10f, 10f)"
        $newLines += "                close()"
        $newLines += "                // Ray 8 (top-left)"
        $newLines += "                moveTo(13.5f, 9f)"
        $newLines += "                lineTo(12f, 7.5f)"
        $newLines += "                lineTo(13f, 7f)"
        $newLines += "                close()"
        $newLines += "            }"
        $newLines += "            // Full sun circle"
        $newLines += "            path("
        $newLines += "                fill = androidx.compose.ui.graphics.SolidColor(androidx.compose.ui.graphics.Color(0xFFFFB74D))"
        $newLines += "            ) {"
        $newLines += "                moveTo(18f, 11f)"
        $newLines += "                arcTo(3f, 3f, 0f, true, true, 12f, 11f)"
        $newLines += "                arcTo(3f, 3f, 0f, true, true, 18f, 11f)"
        $newLines += "                close()"
        $newLines += "            }"
        $newLines += "            // Mountain silhouette"
        $newLines += "            path("
        $newLines += "                fill = androidx.compose.ui.graphics.SolidColor(androidx.compose.ui.graphics.Color.Black)"
        $newLines += "            ) {"
        $newLines += "                moveTo(2f, 18f)"
        $newLines += "                lineTo(8f, 10f)"
        $newLines += "                lineTo(12f, 14f)"
        $newLines += "                lineTo(16f, 8f)"
        $newLines += "                lineTo(22f, 16f)"
        $newLines += "                lineTo(22f, 18f)"
        $newLines += "                close()"
        $newLines += "            }"
        $newLines += "        }.build()"
        $newLines += ""
        $newLines += "    val Afternoon: ImageVector"
        $newLines += "        get() = ImageVector.Builder("
        $newLines += "            name = `"Afternoon`","
        $newLines += "            defaultWidth = 24.0.dp,"
        $newLines += "            defaultHeight = 24.0.dp,"
        $newLines += "            viewportWidth = 24.0f,"
        $newLines += "            viewportHeight = 24.0f"
        $newLines += "        ).apply {"
        $newLines += "            // Sun rays (8 rays)"
        $newLines += "            path("
        $newLines += "                fill = androidx.compose.ui.graphics.SolidColor(androidx.compose.ui.graphics.Color(0xFFFFE082)),"
        $newLines += "                fillAlpha = 0.8f"
        $newLines += "            ) {"
        $newLines += "                // Ray 1 (top)"
        $newLines += "                moveTo(12f, 2f)"
        $newLines += "                lineTo(12.5f, 0f)"
        $newLines += "                lineTo(11.5f, 0f)"
        $newLines += "                close()"
        $newLines += "                // Ray 2 (top-right)"
        $newLines += "                moveTo(14.5f, 3f)"
        $newLines += "                lineTo(16f, 1.5f)"
        $newLines += "                lineTo(15f, 1f)"
        $newLines += "                close()"
        $newLines += "                // Ray 3 (right)"
        $newLines += "                moveTo(16f, 5.5f)"
        $newLines += "                lineTo(18f, 5.5f)"
        $newLines += "                lineTo(18f, 4.5f)"
        $newLines += "                close()"
        $newLines += "                // Ray 4 (bottom-right)"
        $newLines += "                moveTo(14.5f, 7f)"
        $newLines += "                lineTo(16f, 8.5f)"
        $newLines += "                lineTo(15f, 9f)"
        $newLines += "                close()"
        $newLines += "                // Ray 5 (bottom)"
        $newLines += "                moveTo(12f, 8f)"
        $newLines += "                lineTo(12.5f, 10f)"
        $newLines += "                lineTo(11.5f, 10f)"
        $newLines += "                close()"
        $newLines += "                // Ray 6 (bottom-left)"
        $newLines += "                moveTo(9.5f, 7f)"
        $newLines += "                lineTo(8f, 8.5f)"
        $newLines += "                lineTo(9f, 9f)"
        $newLines += "                close()"
        $newLines += "                // Ray 7 (left)"
        $newLines += "                moveTo(8f, 5.5f)"
        $newLines += "                lineTo(6f, 5.5f)"
        $newLines += "                lineTo(6f, 4.5f)"
        $newLines += "                close()"
        $newLines += "                // Ray 8 (top-left)"
        $newLines += "                moveTo(9.5f, 3f)"
        $newLines += "                lineTo(8f, 1.5f)"
        $newLines += "                lineTo(9f, 1f)"
        $newLines += "                close()"
        $newLines += "            }"
        $newLines += "            // Full sun circle"
        $newLines += "            path("
        $newLines += "                fill = androidx.compose.ui.graphics.SolidColor(androidx.compose.ui.graphics.Color(0xFFFFB74D))"
        $newLines += "            ) {"
        $newLines += "                moveTo(15f, 5f)"
        $newLines += "                arcTo(3f, 3f, 0f, true, true, 9f, 5f)"
        $newLines += "                arcTo(3f, 3f, 0f, true, true, 15f, 5f)"
        $newLines += "                close()"
        $newLines += "            }"
        $newLines += "            // Mountain silhouette"
        $newLines += "            path("
        $newLines += "                fill = androidx.compose.ui.graphics.SolidColor(androidx.compose.ui.graphics.Color.Black)"
        $newLines += "            ) {"
        $newLines += "                moveTo(2f, 18f)"
        $newLines += "                lineTo(8f, 10f)"
        $newLines += "                lineTo(12f, 14f)"
        $newLines += "                lineTo(16f, 8f)"
        $newLines += "                lineTo(22f, 16f)"
        $newLines += "                lineTo(22f, 18f)"
        $newLines += "                close()"
        $newLines += "            }"
        $newLines += "        }.build()"
        $newLines += ""
        continue
    }
    
    # Stop skipping when we find Evening
    if ($skipUntilEvening -and $line -match 'val Evening') {
        $skipUntilEvening = $false
        $newLines += $line
        continue
    }
    
    # Skip lines while in TimeIcons reconstruction zone
    if ($skipUntilEvening) {
        continue
    }
    
    $newLines += $line
}

Set-Content $file $newLines

Write-Host "Done! Added full sun circles with 8 rays each"
